#!/usr/bin/env bash
# Initialize Sonarr and Radarr test stack, extract API keys, write to .env

set -e

SONARR_URL="http://localhost:8989"
RADARR_URL="http://localhost:7878"
SONARR_CONFIG_DIR="./sonarr-config"
RADARR_CONFIG_DIR="./radarr-config"
ENV_FILE=".env"
MAX_RETRIES=60
RETRY_DELAY=2

echo "=== ProfSync Test Stack Initializer ==="
echo

# Function to wait for service to be ready
wait_for_service() {
    local url=$1
    local name=$2
    local retries=0

    echo "Waiting for $name to be ready..."
    while [ $retries -lt $MAX_RETRIES ]; do
        if curl -s "$url/api/v3/system/status" > /dev/null 2>&1; then
            echo "✓ $name is ready"
            return 0
        fi
        retries=$((retries + 1))
        if [ $((retries % 10)) -eq 0 ]; then
            echo "  Still waiting... ($retries/$MAX_RETRIES)"
        fi
        sleep $RETRY_DELAY
    done

    echo "✗ $name did not become ready after $((MAX_RETRIES * RETRY_DELAY)) seconds"
    return 1
}

# Function to extract API key from config
get_api_key() {
    local config_file=$1
    local app_name=$2

    if [ ! -f "$config_file" ]; then
        echo "✗ Config file not found: $config_file"
        return 1
    fi

    # Extract API key from config.xml
    local api_key=$(grep -oP '(?<=<ApiKey>)[^<]+' "$config_file" 2>/dev/null || echo "")

    if [ -z "$api_key" ]; then
        echo "✗ Could not extract API key from $app_name config"
        return 1
    fi

    echo "$api_key"
}

# Step 1: Start Docker Compose
echo "Starting Docker Compose..."
docker-compose up -d
echo "✓ Containers started"
echo

# Step 2: Wait for Sonarr
if ! wait_for_service "$SONARR_URL" "Sonarr"; then
    echo "ERROR: Sonarr failed to start"
    exit 1
fi

# Step 3: Wait for Radarr
if ! wait_for_service "$RADARR_URL" "Radarr"; then
    echo "ERROR: Radarr failed to start"
    exit 1
fi
echo

# Step 4: Extract API keys
echo "Extracting API keys..."
SONARR_API_KEY=$(get_api_key "$SONARR_CONFIG_DIR/config.xml" "Sonarr")
if [ -z "$SONARR_API_KEY" ]; then
    echo "✗ Failed to extract Sonarr API key"
    exit 1
fi
echo "✓ Sonarr API key: ${SONARR_API_KEY:0:10}..."

RADARR_API_KEY=$(get_api_key "$RADARR_CONFIG_DIR/config.xml" "Radarr")
if [ -z "$RADARR_API_KEY" ]; then
    echo "✗ Failed to extract Radarr API key"
    exit 1
fi
echo "✓ Radarr API key: ${RADARR_API_KEY:0:10}..."
echo

# Step 4b: Validate API keys actually work
echo "Validating API keys..."
SONARR_STATUS=$(curl -sf -H "X-Api-Key: $SONARR_API_KEY" "$SONARR_URL/api/v3/system/status" 2>/dev/null) || {
    echo "✗ Sonarr API key is invalid (got non-200 response)"
    exit 1
}
echo "✓ Sonarr API key works"

RADARR_STATUS=$(curl -sf -H "X-Api-Key: $RADARR_API_KEY" "$RADARR_URL/api/v3/system/status" 2>/dev/null) || {
    echo "✗ Radarr API key is invalid (got non-200 response)"
    exit 1
}
echo "✓ Radarr API key works"
echo

# Step 5: Create/update .env file
echo "Writing to $ENV_FILE..."
cat > "$ENV_FILE" << EOF
# ProfSync Test Stack Configuration
# Generated by init-stack.sh

# Sonarr
SONARR_URL=http://localhost:8989
SONARR_API_KEY=$SONARR_API_KEY

# Radarr
RADARR_URL=http://localhost:7878
RADARR_API_KEY=$RADARR_API_KEY
EOF

echo "✓ .env file created"
echo

# Step 6: Fix directory permissions (so containers can write)
echo "Fixing directory permissions..."
docker exec profsync-sonarr chmod 777 /tv /downloads 2>/dev/null || true
docker exec profsync-radarr chmod 777 /movies /downloads 2>/dev/null || true
sleep 2
echo

# Step 6b: Create root folders
echo "Configuring root folders..."

# Sonarr TV root folder
curl -s -X POST "$SONARR_URL/api/v3/rootfolder" \
  -H "X-Api-Key: $SONARR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"path": "/tv", "accessible": true, "freeSpace": 1000000000}' > /dev/null 2>&1 && \
  echo "✓ Sonarr TV root folder created" || echo "✓ Sonarr TV root folder (already exists)"

# Radarr Movies root folder
curl -s -X POST "$RADARR_URL/api/v3/rootfolder" \
  -H "X-Api-Key: $RADARR_API_KEY" \
  -H "Content-Type: application/json" \
  -d '{"path": "/movies", "accessible": true, "freeSpace": 1000000000}' > /dev/null 2>&1 && \
  echo "✓ Radarr Movies root folder created" || echo "✓ Radarr Movies root folder (already exists)"
echo

# Step 7: Configure authentication (skipped by default for test stack - uncomment to enable)
# Note: Auth configuration can be finicky. For testing, we skip it and you can login via web UI
# if [ "$1" != "--no-auth" ]; then
#   echo "Configuring authentication..."
#   bash "$(dirname "$0")/configure-auth.sh" "$SONARR_URL" "$SONARR_API_KEY" "$RADARR_URL" "$RADARR_API_KEY" "testuser" "testpass123" || \
#     echo "⚠️  Warning: Auth configuration may have failed"
#   echo
# fi

# Step 8: Import test fixtures (optional, can be skipped with --no-fixtures)
if [ "$1" != "--no-fixtures" ]; then
  if [ -d "$(dirname "$0")/fixtures" ]; then
    echo "Importing test fixtures (this may take a minute)..."
    bash "$(dirname "$0")/import-fixtures.sh" "$SONARR_URL" "$SONARR_API_KEY" "$RADARR_URL" "$RADARR_API_KEY" || \
      echo "⚠️  Warning: Some fixtures may not have imported"
    echo
  fi
fi

# Step 7: Summary
echo "=== Test Stack Ready ==="
echo
echo "Sonarr:"
echo "  URL: $SONARR_URL"
echo "  Web: http://localhost:8989"
echo "  API Key: $SONARR_API_KEY"
echo
echo "Radarr:"
echo "  URL: $RADARR_URL"
echo "  Web: http://localhost:7878"
echo "  API Key: $RADARR_API_KEY"
echo
echo "Run the wizard with:"
echo "  python ../wizard.py --teststack"
echo

# Step 9: Run post-deployment validation
echo "Running post-deployment validation..."
echo
bash "$(dirname "$0")/validate-stack.sh"
